library(ape)
library(ggplot2)
library(reshape2)
library(phangorn)
library(MASS)
library(GGally)
source("clade.freq.R")
source("cumulative.freq.R")
source("slide.freq.R")
source("plawty.R")
source("compare.n.R")
source("tree.ess.R")
source("tree.dist.matrix.R")
source("mds.treespace.R")
source("continuous.ess.R")
source("parse.clades.R")
source("load.trees.R")
source("analyse.rwty.R")
source("pairwise.RF.R")

# test