#' Perform sliding window analysis of discordance among chains.
#' 
#' This function takes analyze.multu output, an optional array of names for those
#' files.  It returns a plot of the change in discordance
#'
#' @param x A list generated by analyze.multi
#' @param setnames A list of names for the chains.
#'
#' @return output A list containing for each window: a table of frequencies of each clade in each chain, a distance matrix measuring discordance, and an hclust plot.
#'
#' @keywords MCMC, phylogenetics, discordance, sliding window
#'
#' @export
#' 
#' @examples
#' discordance.n(myAnalyze.multi.object, setnames=c("Chain 1", "Chain 2", "Chain 3"))

discordance.n <- function(x, setnames=NA){ # x is a list generated by analyze multi ??-TODO allow chains, burnin and window.size to be passed-??
  # set initial values
  sets <- length(x)-1
  slide.wins <- ncol(x[[1]]$slide.data$slide.table)-2
  output <- list(length=slide.wins)

  #populate clade frequency tables, one for each sliding window
  for(i in 1:slide.wins){
    #attach tip names to clade frequencies for the first chain(necessary because clade name/numbers may not match among chains)
    winTable <- data.frame(cbind(x[[1]]$slide.data$translation[,3],x[[1]]$slide.data$slide.table[,i]), stringsAsFactors=FALSE)
    colnames(winTable) <- c("Tip names",names(x)[1])
    class(winTable[,2]) <- "numeric"
    # Populate the rest of the table, one chain at a time
    for (j in 2:sets){
      thisTable <- data.frame(cbind(x[[j]]$slide.data$translation[,3],x[[j]]$slide.data$slide.table[,i]), stringsAsFactors=FALSE)
      colnames(thisTable) <- c("Tip names",names(x)[j])
      winTable <- merge(winTable,thisTable, by="Tip names", all=TRUE)
      winTable[is.na(winTable)] <- 0
      class(winTable[,j+1]) <- "numeric"
    }
    #Various options for output, one list per window, or list of tables, list of 
    # discordance matrices and a multiphylo object. DAN - preferences?    
    win.out <- list()
    discordance <- discordance.mat(winTable)
    win.out <- list("window.table" = winTable, "discordance.dist" = discordance, "discordance.tree" = as.phylo(hclust(discordance)))
    output[[i]] <- win.out
    names(output)[i] <- paste("window",i,sep=".")
  }     
output
}
